-- CreateTable
CREATE TABLE `monitoramento_cota_solidariedade` (
    `id` VARCHAR(191) NOT NULL,
    `processo_id` VARCHAR(191) NOT NULL,
    `ficha_ouc` INTEGER NULL,
    `proposta_oodc` INTEGER NULL,
    `data_informacao_dmus` DATE NULL,
    `setor` VARCHAR(191) NULL,
    `quadra` VARCHAR(191) NULL,
    `lote` TEXT NULL,
    `lote_atualizado_sqcond` VARCHAR(191) NULL,
    `codigo_logradouro` VARCHAR(191) NULL,
    `endereco` TEXT NULL,
    `proprietario_interessado` TEXT NULL,
    `distrito` VARCHAR(191) NULL,
    `subprefeitura` VARCHAR(191) NULL,
    `macrozona` TEXT NULL,
    `macroarea` TEXT NULL,
    `subsetor` VARCHAR(191) NULL,
    `zona_uso` VARCHAR(191) NULL,
    `subcategoria_uso` TEXT NULL,
    `coeficiente_utilizado` DECIMAL(10, 4) NULL,
    `area_terreno` DECIMAL(14, 2) NULL,
    `valor_m2_quadro14` DECIMAL(14, 2) NULL,
    `alvara_aprovacao` TEXT NULL,
    `alvara_execucao` TEXT NULL,
    `certificado_conclusao` TEXT NULL,
    `observacao` TEXT NULL,
    `origem` ENUM('SISACOE', 'SEI', 'APROVA_DIGITAL', 'OUTRO') NULL,
    `area_habitacao_social` VARCHAR(191) NULL,
    `situacao_cota` TEXT NULL,
    `modalidade` VARCHAR(191) NULL,
    `unidades` VARCHAR(191) NULL,
    `estimativa_deposito_fundurb` DECIMAL(14, 2) NULL,
    `valor_calculado_processo` DECIMAL(14, 2) NULL,
    `valor_pago` TEXT NULL,
    `valor_devido` TEXT NULL,
    `comprovantes_pagamento_prodam` TEXT NULL,
    `planilha_calculo_cota` ENUM('CONSTA', 'NAO_CONSTA', 'NAO_SE_APLICA') NULL,
    `termo_compromisso_portaria` ENUM('CONSTA', 'NAO_CONSTA', 'NAO_SE_APLICA') NULL,
    `solicitacao_dsiz` TEXT NULL,
    `preenchimento_qgis` TEXT NULL,
    `observacoes` TEXT NULL,
    `ficha_revisada_em` DATE NULL,
    `area_construida_computavel_total` DECIMAL(14, 2) NULL,
    `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `alterado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `monitoramento_cota_solidariedade_processo_id_key`(`processo_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `monitoramento_cota_solidariedade` ADD CONSTRAINT `monitoramento_cota_solidariedade_processo_id_fkey` FOREIGN KEY (`processo_id`) REFERENCES `processos`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
